name: CI

on:
    push:
        branches: ["main", "master"]
    pull_request:
        branches: ["main", "master"]

jobs:
    test:
        runs-on: ubuntu-latest

        services:
            mysql:
                image: mysql:8.0
                env:
                    MYSQL_ROOT_PASSWORD: localhost
                    MYSQL_DATABASE: ma_bdd
                    MYSQL_USER: db_user
                    MYSQL_PASSWORD: db_pwd
                ports:
                    - 3307:3306
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

        steps:
            - uses: actions/checkout@v3

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: "8.2"
                  extensions: pdo, pdo_mysql

            - name: Install dependencies
              run: composer install

            - name: Wait for MySQL
              run: sleep 10

            - name: Initialize database
              run: mysql -h127.0.0.1 -P3307 -uuser -ppassword maintenanceapp < init.sql

            - name: Start PHP server
              run: php -S localhost:8083 &

            - name: Wait for server
              run: sleep 3

            - name: Run tests
              run: vendor/bin/phpunit tests/

            - name: Run linter
              run: composer lint

    deploy:
        needs: test
        if: github.ref == 'refs/heads/main'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4.1.1

            - name: FTP Deploy
              uses: SamKirkland/FTP-Deploy-Action@v4.3.5
              with:
                  server: ${{ secrets.FTP_HOST }}
                  username: ${{ secrets.FTP_USERNAME }}
                  password: ${{ secrets.FTP_PASSWORD }}
                  server-dir: Natisrt/
